#!/bin/sh
# pre-commit: the staged Go files are gofmt-formatted, group their imports
# the way the linter wants, carry the licence notice, build no outbound HTTP
# client without a trace, and hold no code the standard library already
# covers. The checks live in lateregate; this file only calls it.
# Install with: git config core.hooksPath .githooks
exec go tool lateregate hook
